name: pws_watcher
description: Mobile application for Personal Weather Station monitoring.

version: 99.99.99+99

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  connectivity: ^3.0.6
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_iconpicker: ^3.1.2
  flutter_svg: ^1.0.1
  get_it: ^7.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  http: ^0.13.4
  image_downloader: ^0.31.0
  launch_review: ^3.0.1
  overlay_support: ^1.2.1
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  photo_view: ^0.13.0
  provider: ^6.0.2
  rxdart: ^0.27.3
  shared_preferences: ^2.0.12
  showcaseview: ^1.1.4
  url_launcher: ^6.0.18
  xml: ^5.3.1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/current_weather/
    - assets/flare/
    - assets/values.json
