name: pws_watcher
description: Mobile application for Personal Weather Station monitoring.

version: 1.8.3+30

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^3.5.0
  http: ^0.12.0+3
  flutter_svg: ^0.15.0
  shared_preferences: ^0.5.6
  flare_flutter: ^1.8.3
  connectivity: ^0.4.6+1
  provider: ^4.0.1
  hive: ^1.2.0
  hive_flutter: ^0.2.1
  rxdart: ^0.23.1
  get_it: ^3.1.0
  path_provider: ^1.5.1
  showcaseview: ^0.1.3
  url_launcher: ^5.4.1
  flushbar: "1.9.1"
  launch_review: ^2.0.0
  photo_view: ^0.9.1
  permission_handler: ^4.2.0+hotfix.3
  image_downloader: ^0.19.1
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.6.0
  build_runner: ^1.7.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/current_weather/
    - assets/flare/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
