name: pws_watcher
description: Public Weather Station Watcher flutter application.

version: 1.1.0+6

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^3.4.1
  http: ^0.12.0+2
  flutter_svg: any
  shared_preferences: ^0.5.2
  fluro: ^1.4.0
  cupertino_icons: ^0.1.2
  highlighter_coachmark: ^0.0.3
  flare_flutter: ^1.5.0
  connectivity: ^0.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
      - assets/
      - assets/images/
      - assets/flare/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
