name: pws_watcher
description: Mobile application for Personal Weather Station monitoring.

version: 99.99.99+99

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  connectivity: ^0.4.9+5
  flare_flutter: ^2.0.6
  flushbar: ^1.10.4
  flutter_iconpicker: ^2.2.2
  flutter_svg: ^0.19.1
  get_it: ^5.0.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  http: ^0.12.2
  image_downloader: ^0.20.1
  launch_review: ^2.0.0
  path_provider: ^1.6.21
  permission_handler: ^5.0.1+1
  photo_view: ^0.10.2
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  shared_preferences: ^0.5.12+2
  showcaseview: ^0.1.6
  url_launcher: ^5.7.5
  xml: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  hive_generator: ^0.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/current_weather/
    - assets/flare/
    - assets/values.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
