name: pws_watcher
description: Public Weather Station Watcher flutter application.

version: 1.4.3+18

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^3.5.0
  http: ^0.12.0+2
  flutter_svg: ^0.15.0
  shared_preferences: ^0.5.4+8
  cupertino_icons: ^0.1.3
  highlighter_coachmark: ^0.0.3
  flare_flutter: ^1.8.0
  connectivity: ^0.4.6
  provider: ^3.2.0
  hive: ^1.1.1
  hive_flutter: ^0.2.1
  rxdart: ^0.22.6
  get_it: ^3.0.3
  path_provider: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.5.2
  build_runner: ^1.7.1


flutter:

  uses-material-design: true

  assets:
      - assets/
      - assets/images/
      - assets/flare/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
